user_list = [{"user_id": 1,
              "email": "thomascarter@reqres.in",
              "first_name": "Thomas",
              "last_name": "Carter",
              "avatar": "https://cdn.discordapp.com/attachments/168439091824689152/712379647672975400/yepcock.png",
              },
             {"user_id": 2,
              "email": "lewis.bowden@reqres.in",
              "first_name": "Lewis",
              "last_name": "Bowden",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 3,
              "email": "joe.smith@reqres.in",
              "first_name": "Joe",
              "last_name": "Smith",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 4,
              "email": "muhammed.clark@reqres.in",
              "first_name": "Muhammad",
              "last_name": "Clark",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 5,
              "email": "steve.rogers@reqres.in",
              "first_name": "Steve",
              "last_name": "Rogers",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 6,
              "email": "alex.hillr@reqres.in",
              "first_name": "Alex",
              "last_name": "Hill",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 7,
              "email": "bob.smith@reqres.in",
              "first_name": "Bob",
              "last_name": "Smith",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 8,
              "email": "lucie.higgins@reqres.in",
              "first_name": "Lucie",
              "last_name": "Higgins",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 9,
              "email": "sophie.brown@reqres.in",
              "first_name": "Sophie",
              "last_name": "Brown",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 10,
              "email": "jasmine.hunt@reqres.in",
              "first_name": "Jasmine",
              "last_name": "Hunt",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 11,
              "email": "carl.wheezer@reqres.in",
              "first_name": "Carl",
              "last_name": "Wheezer",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 12,
              "email": "pepe.ga@reqres.in",
              "first_name": "Pepe",
              "last_name": "Ga",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 13,
              "email": "james.jameson@reqres.in",
              "first_name": "James",
              "last_name": "Jameson",
              "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/josephstein/128.jpg",
              },
             {"user_id": 14,
              "email": "ovuvuevuevue.enyetuenwuevue.ugbemugbem.osas@reqres.in",
              "first_name": "Ovuvuevuevue Enyetuenwuevue",
              "last_name": "Ugbemugbem Osas",
              "avatar": "https://i.redd.it/hu6eqi6fj8f31.jpg",
              }
             ]
